services:
  stationary-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - MongoDb__ConnectionString=mongodb+srv://naikamit6773_db_user:99Vm5HDAzFmUZaGM@cluster0.2gdsncu.mongodb.net/?appName=Cluster0
      - MongoDb__DatabaseName=StationaryDB
      - ServiceUrls__CommonService=http://host.docker.internal:8091
    extra_hosts:
      - "host.docker.internal:host-gateway"

  stationary-frontend:
    build:
      context: ./Stationary.Frontend
      dockerfile: Dockerfile
    ports:
      - "4202:80"
    depends_on:
      - stationary-api

