services:
  stationary-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      # We commented this out so your appsettings.json link takes priority!
      # - MongoDb__ConnectionString=mongodb://stationary-db:27017
      - MongoDb__DatabaseName=StationaryDB

  stationary-frontend:
    build:
      context: ./Stationary.Frontend
      dockerfile: Dockerfile
    ports:
      - "4202:80"
    depends_on:
      - stationary-api

