<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.10.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.10.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Stationary.Context\Stationary.Context.csproj" />
    <ProjectReference Include="..\Stationary.DMO\Stationary.DMO.csproj" />
    <ProjectReference Include="..\Stationary.DTO\Stationary.DTO.csproj" />
  </ItemGroup>
</Project>
